export const mockCandidates = [
  {
    id: "cand_001",
    job_id: "job_001", // Frontend Developer
    full_name: "Aurelie Yukiko",
    email: "aurelieyukiko@yahoo.com",
    phone: "082120908766",
    birth_date: "30 January 2001",
    domicile: "Jakarta",
    gender: "Female",
    linkedin: "https://www.linkedin.com/in/aurelieyukiko",
    applied_date: "2025-10-05",
  },
  {
    id: "cand_002",
    job_id: "job_001",
    full_name: "Dityo Hendyawan",
    email: "dityohendyawan@yahoo.com",
    phone: "081184180678",
    birth_date: "30 January 2001",
    domicile: "Jakarta",
    gender: "Male",
    linkedin: "https://www.linkedin.com/in/dityohendyawan",
    applied_date: "2025-10-06",
  },
  {
    id: "cand_003",
    job_id: "job_001",
    full_name: "Mira Workman",
    email: "miraworkman@yahoo.com",
    phone: "081672007108",
    birth_date: "30 January 2001",
    domicile: "Jakarta",
    gender: "Female",
    linkedin: "https://www.linkedin.com/in/miraworkman",
    applied_date: "2025-10-06",
  },
  {
    id: "cand_004",
    job_id: "job_001",
    full_name: "Emerson Baptista",
    email: "emersonbaptista@yahoo.com",
    phone: "082167008244",
    birth_date: "30 January 2001",
    domicile: "Jakarta",
    gender: "Male",
    linkedin: "https://www.linkedin.com/in/emersonbaptista",
    applied_date: "2025-10-07",
  },
  {
    id: "cand_005",
    job_id: "job_001",
    full_name: "Indra Zein",
    email: "indrazein@yahoo.com",
    phone: "081181630568",
    birth_date: "30 January 2001",
    domicile: "Jakarta",
    gender: "Male",
    linkedin: "https://www.linkedin.com/in/indrazein",
    applied_date: "2025-10-08",
  },
  {
    id: "cand_006",
    job_id: "job_002", // UI/UX Designer
    full_name: "Joyce Adelina",
    email: "joyce@yahoo.com",
    phone: "084288771015",
    birth_date: "30 January 2001",
    domicile: "Bandung",
    gender: "Female",
    linkedin: "https://www.linkedin.com/in/joyceadelina",
    applied_date: "2025-10-09",
  },
  {
    id: "cand_007",
    job_id: "job_002",
    full_name: "Javon Saputra",
    email: "javon@yahoo.com",
    phone: "083283445502",
    birth_date: "30 January 2001",
    domicile: "Bandung",
    gender: "Male",
    linkedin: "https://www.linkedin.com/in/javonsaputra",
    applied_date: "2025-10-09",
  },
  {
    id: "cand_008",
    job_id: "job_002",
    full_name: "Ella Gracia",
    email: "ella@yahoo.com",
    phone: "088306913834",
    birth_date: "30 January 2001",
    domicile: "Bandung",
    gender: "Female",
    linkedin: "https://www.linkedin.com/in/ellagracia",
    applied_date: "2025-10-10",
  },
];
