export const mockJobs = [
  {
    id: "job_001",
    slug: "frontend-developer",
    title: "Frontend Developer",
    department: "Engineering",
    description:
      "We are looking for a Frontend Developer who is passionate about building intuitive and responsive interfaces. You will work closely with UI/UX designers and backend engineers to deliver seamless user experiences.",
    requirement:
      "Proficient in React.js, JavaScript, HTML, and CSS. Experience with REST APIs, responsive design, and Git version control. Strong understanding of UI/UX principles and good communication skills.",
    status: "active",
    job_type: "Full-time",
    location: "Batam",
    job_started: "10 October 2025",
    posted_date: "2025-09-30",
    closing_date: "2025-11-30",
    total_applicants: 5,
    created_by: "Admin Rakamin",
    tags: ["React", "Frontend", "JavaScript"],
    experience_level: "Mid-level",
    education: "Bachelor's Degree in Computer Science",
    salary_range: {
      min: 7000000,
      max: 8000000,
      currency: "IDR",
      display_text: "Rp7.000.000 - Rp8.000.000",
    },
  },
  {
    id: "job_002",
    slug: "ui-ux-designer",
    title: "UI/UX Designer",
    department: "Design",
    description:
      "Join our creative design team to craft intuitive interfaces and seamless user experiences. You will collaborate closely with developers and product managers to deliver high-quality designs.",
    requirement:
      "Proficient in Figma, Adobe XD, or Sketch. Strong understanding of user-centered design principles and design systems. Excellent communication and collaboration skills.",
    status: "active",
    job_type: "Contract",
    location: "Jakarta",
    job_started: "01 November 2025",
    posted_date: "2025-10-01",
    closing_date: "2025-12-01",
    total_applicants: 3,
    created_by: "Admin Rakamin",
    tags: ["UI/UX", "Figma", "Design System"],
    experience_level: "Junior",
    education: "Bachelor's Degree in Visual Design",
    salary_range: {
      min: 6000000,
      max: 7500000,
      currency: "IDR",
      display_text: "Rp6.000.000 - Rp7.500.000",
    },
  },
];
